/*
* generated by Xtext
*/
package fr.inria.atlanmod.governance.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.atlanmod.governance.services.StrategyGrammarAccess;

public class StrategyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StrategyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.atlanmod.governance.parser.antlr.internal.InternalStrategyParser createParser(XtextTokenStream stream) {
		return new fr.inria.atlanmod.governance.parser.antlr.internal.InternalStrategyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Project";
	}
	
	public StrategyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StrategyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
