/*
* generated by Xtext
*/
package fr.inria.atlanmod.decision.ui.contentassist;

import fr.inria.atlanmod.decision.ui.contentassist.AbstractStrategyProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StrategyProposalProvider extends AbstractStrategyProposalProvider {

}
