/*
* generated by Xtext
*/
package fr.inria.atlanmod.decision.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StrategyAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/atlanmod/decision/parser/antlr/internal/InternalStrategy.tokens");
	}
}
