/*
 * generated by Xtext
 */
package fr.inria.atlanmod.decision.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StrategyUiModule extends fr.inria.atlanmod.decision.ui.AbstractStrategyUiModule {
	public StrategyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
