/*
 * generated by Xtext
 */
package fr.inria.atlanmod.governance;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StrategyRuntimeModule extends fr.inria.atlanmod.governance.AbstractStrategyRuntimeModule {

}
