<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Collaboration" nsURI="http://atlanmod.fr/collaboration" nsPrefix="collaboration">
  <eClassifiers xsi:type="ecore:EClass" name="Interactions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collaborations" upperBound="-1"
        eType="#//Collaboration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisions" upperBound="-1"
        eType="#//Decision" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vote">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arePart" eType="#//Decision"
        eOpposite="#//Decision/votes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="votedBy" eType="#//User"
        eOpposite="#//User/votes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agreement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="votes" upperBound="-1"
        eType="#//Vote" eOpposite="#//Vote/votedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leads" upperBound="-1"
        eType="#//Collaboration" eOpposite="#//Collaboration/leader"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="ecore:EClass ../../fr.inria.atlanmod.governance.strategy/model/strategy.ecore#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collaboration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" upperBound="-1"
        eType="#//Metadata" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../fr.inria.atlanmod.governance.strategy/model/strategy.ecore#//CollaborationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="votes" upperBound="-1"
        eType="#//Vote" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leader" eType="#//User"
        eOpposite="#//User/leads"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isDecided" upperBound="-1"
        eType="#//Decision" eOpposite="#//Decision/decides"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accepted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="votes" upperBound="-1"
        eType="#//Vote" eOpposite="#//Vote/arePart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decides" eType="#//Collaboration"
        eOpposite="#//Collaboration/isDecided"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategy" eType="ecore:EClass ../../fr.inria.atlanmod.governance.strategy/model/strategy.ecore#//Strategy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metadata"/>
  <eClassifiers xsi:type="ecore:EClass" name="Priority" eSuperTypes="#//Metadata">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagBased" eSuperTypes="#//Metadata">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//Tag"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
