/*
* generated by Xtext
*/
package fr.inria.atlanmod.decision.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class StrategyOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
